# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckl_base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='description',
        ),
        migrations.AddField(
            model_name='outlet',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
